# Generated by Django 3.2.5 on 2021-07-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Market',
            new_name='Marker',
        ),
    ]
